### ISSUE TITLE
Optimizer zero grad performed after ema update

### ISSUE THREAD

**Issue by NanoCode012** [MagicFrogSJTU/yolov5#2]
https://github.com/MagicFrogSJTU/yolov5/blob/96fa40a3a925e4ffd815fe329e1b5181ec92adc8/train.py#L313-L316

Hello, may I understand why you perform `optimizer.zero_grad()` after `ema.update(model)`?
Also, is there a reason to call `.cuda.synchronize()` in optimize? I read that DDP will perform synchronize when it's needed.

**Comment by MagicFrogSJTU** [comment]
These actually doesn't make sense.
Just add them to keep the code similar to others.
You can saftely keep the original way.
