### ISSUE TITLE
DDP update

### ISSUE THREAD

**Issue by NanoCode012** [MagicFrogSJTU/yolov5#7]
https://github.com/MagicFrogSJTU/yolov5/blob/5bf8bebe8873afb18b762fe1f409aca116fac073/utils/datasets.py#L62

Should we do `os.cpu_count()/world_size`? For 2, this might not be an issue, but if this code is expanded to 4 or 8, it's good to not have 4\*8=32 or 8\*8=64 concurrent dataloaders if their CPU count is lower than it?

**Comment by NanoCode012** [comment]
Should we add a GPU core count check? No more than 2 for DDP mode?

**Comment by MagicFrogSJTU** [comment]
> Should we add a GPU core count check? No more than 2 for DDP mode?

Yes. I think so

**Comment by MagicFrogSJTU** [comment]
> https://github.com/MagicFrogSJTU/yolov5/blob/5bf8bebe8873afb18b762fe1f409aca116fac073/utils/datasets.py#L62
> 
> Should we do `os.cpu_count()/world_size`? For 2, this might not be an issue, but if this code is expanded to 4 or 8, it's good to not have 4*8=32 or 8*8=64 concurrent dataloaders if their CPU count is lower than it?

Yes, I think so

**Comment by MagicFrogSJTU** [comment]
@NanoCode012 Is there a way that both of us can work on the same branch?

**Comment by NanoCode012** [comment]
> @NanoCode012 Is there a way that both of us can work on the same branch?

If you add me as collaborator, I think it would work. Under the settings for this branch. 

It's quite troublesome to fork. Then PR to that fork from this new branch each time.

**Comment by MagicFrogSJTU** [comment]
> > @NanoCode012 Is there a way that both of us can work on the same branch?
> 
> If you add me as collaborator, I think it would work. Under the settings for this branch.
> 
> It's quite troublesome to fork. Then PR to that fork from this new branch each time.

Let me do this!

**Comment by MagicFrogSJTU** [comment]
exp | gpus | has syncBN | extra config | epoch1 | epoch2 | epoch3 | epoch4 | epoch5 | train speed(min/epoch) |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
default | 1 | \ | \ | 1.13 | 6.43 | 12.2 | 19 | 23.9 | 14 |  
DDP | 2 | Yes | \ | 0.659 | 5.77 | 12.2 | 18.8 | 23.6 | 11 |  
0.558 | 5.93 | 12.7 | 18.4 | \ |  
DDP | 2 | No | \ | 1.1 | 6.42 | 12.9 | 19.3 | 23.9 | 8-9 |  
DDP | 4 | Yes | \ | 5.17 | 3.82 | 7.34 | 19.3 | \ | 9 |  
DDP | 4 | No | \ | 6.11 | 4.2 | 7.66 | 12.6 | 16.3 |   |  
DDP | 4 | No | random_seed= | 5.69 | 4.03 | 7.85 | 12.5 |   |   |

**Comment by NanoCode012** [comment]
I am gonna be a bit occupied for a while. However, I've set the default for 2 GPU running, so you don't need to test that.

Hm, is syncbatch reducing performance? Wow, 5% on first epoch for 4 GPU DDP? Do you mean 0.5%? These numbers are quite interesting.

**Comment by MagicFrogSJTU** [comment]
> I am gonna be a bit occupied for a while. However, I've set the default for 2 GPU running, so you don't need to test that.
> 
> Hm, is syncbatch reducing performance? Wow, 5% on first epoch for 4 GPU DDP? Do you mean 0.5%? These numbers are quite interesting.

Yes, 0.5%. Interesting.

**Comment by NanoCode012** [comment]
I also set 4 GPU DDP(Magic w Sync) to run. It performs similarly to your runs.

Btw, do you run on notebook or terminal? Whenever I run on terminal, I keep getting this issue below where it would keep going new line on each update filling up the terminal, making me lose the history. This also happens for some code and doesn't for others. I can't pinpoint the issue. Doesn't happen for notebook though.
![image](https://user-images.githubusercontent.com/9899957/87403959-b6032c80-c5e7-11ea-88b6-e043b65e6345.png)

**Comment by MagicFrogSJTU** [comment]
> I also set 4 GPU DDP(Magic w Sync) to run. It performs similarly to your runs.
> 
> Btw, do you run on notebook or terminal? Whenever I run on terminal, I keep getting this issue below where it would keep going new line on each update filling up the terminal, making me lose the history. This also happens for some code and doesn't for others. I can't pinpoint the issue. Doesn't happen for notebook though.
> ![image](https://user-images.githubusercontent.com/9899957/87403959-b6032c80-c5e7-11ea-88b6-e043b65e6345.png)

Terminal
When I maximize my terminal size, the log prints as expected.

**Comment by NanoCode012** [comment]
**Table runs:**
Batch size: 64
SyncBatch is _disabled_ for Magic
Trained on V100.

| Branch | GPU | Type | Epoch 1 | Epoch 2 | Epoch 5 | Epoch 10 | Epoch 25 | Train time for epoch 1 | 
| --- | --- | --- | --- | --- | --- | --- | --- | --- | 
| Default | 1 | \ | 0.01226 | 0.06774 | 0.2447| 0.3266 | 0.3957 | -| 
| | 2 | _DP_ | 0.01105 | 0.06385 | 0.2409 | 0.3297 | 0.3907 | 11:50 | 
| | | DDP | 0.01243 | 0.06131 | 0.2411 | 0.3313 | 0.3911 | 11:55 | 
| | 4 | DDP | 0.01167 | 0.06343 | 0.2336 | 0.326 | 0.3906| -| 
| Magic P1 | 1 |  \  | 0.0121 | 0.06502 | -| -| - | 19:42 (CPU bottleneck) | 
|  |   | \ | 0.0131 | 0.06419 | 0.2403 | 0.3359 | 0.3951 | - | 
| | 2 |  DDP | 0.009887 | 0.05979 | 0.2389 | 0.33 | 0.395 | - | 
| Magic Ft | 4 | DDP | 0.00519 | 0.0403 | 0.168 | 0.251 | 0.323 | - | 

_Ft_ is short for Magic feature/DDP-fixed branch
_P1_ is short for Magic Patch 1 branch, which is now behind Feature branch. 

Edit: There may be some bottleneck for train time as I'm running multiple at once in Docker.

**Comment by NanoCode012** [comment]
Do you ever get Warning to set `OMP_NUM_THREADS=1` for stability at the start of the program? It would be good to set it somewhere, like in `torch.select_device` or beginning on `main` for `train.py`.

**Comment by MagicFrogSJTU** [comment]
> Do you ever get Warning to set OMP_NUM_THREADS=1 for stability at the start of the program? It would be good to set it somewhere, like in torch.select_device or beginning on main for train.py.
> 

> ```
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
> ```

It seems OMP_NUM_THREADS is set to 1 in default. Do you mean setting it to a bigger value?

**Comment by NanoCode012** [comment]
Made a mistake editing your comment. I thought I was typing in a new one. 

> It seems OMP_NUM_THREADS is set to 1 in default. Do you mean setting it to a bigger value?

My idea is to just set it here explicitly since it only effects DDP, so in future, no one will create a thread asking what it is.
https://github.com/MagicFrogSJTU/yolov5/blob/e742dd9619d29306c7541821238d3d7cddcdc508/train.py#L454-L462 

I want to play with it, but I'm not sure how to tell. Also, different configurations might cause it to perform better or worse.

**Comment by MagicFrogSJTU** [comment]
> Made a mistake editing your comment. I thought I was typing in a new one.
> 
> > It seems OMP_NUM_THREADS is set to 1 in default. Do you mean setting it to a bigger value?
> 
> My idea is to just set it here explicitly since it only effects DDP, so in future, no one will create a thread asking what it is.
> https://github.com/MagicFrogSJTU/yolov5/blob/e742dd9619d29306c7541821238d3d7cddcdc508/train.py#L454-L462
> 
> I want to play with it, but I'm not sure how to tell. Also, different configurations might cause it to perform better or worse.

Is it affecting performance? Seems weird?

**Comment by MagicFrogSJTU** [comment]
@NanoCode012 
You don't have to make merge request.
Just push your changes to the DDP_fixed branch.

I am making a Work-In-Progress merge request to Glenn's repos.
Let's try finishing all this stuff tomorrow!

**Comment by NanoCode012** [comment]
> Is it affecting performance? Seems weird?

Nope. I've left as it is. When reading other's, it's about CPU count, so it's better not to change it as we have different settings.

> You don't have to make merge request.
> Just push your changes to the DDP_fixed branch.

I wanted to keep things neat. Also, I wanted to test it carefully before merging.

> Let's try finishing all this stuff tomorrow!

Sure!

**Comment by MagicFrogSJTU** [comment]
> > Is it affecting performance? Seems weird?
> 
> Nope. I've left as it is. When reading other's, it's about CPU count, so it's better not to change it as we have different settings.
> 
> > You don't have to make merge request.
> > Just push your changes to the DDP_fixed branch.
> 
> I wanted to keep things neat. Also, I wanted to test it carefully before merging.
> 
> > Let's try finishing all this stuff tomorrow!
> 
> Sure!

Great! I don't have machine resources now.
Glenn have a small test script. If you are available, could you please help run the following script?
```bash
# Unit tests
%%shell
rm -rf yolov5 && git clone https://github.com/ultralytics/yolov5 && cd yolov5
export PYTHONPATH="$PWD" # to run *.py. files in subdirectories
pip install -r requirements.txt onnx
python3 -c "from utils.google_utils import *; gdrive_download('1n_oKgR81BJtqk75b00eAjdv03qVCQn2f', 'coco128.zip')" && mv ./coco128 ../
for x in yolov5s yolov5m yolov5l yolov5x # models
do
  python train.py --weights $x.pt --cfg $x.yaml --epochs 4 --img 320 --device 0  # train
  for di in 0 cpu # inference devices
  do
    python detect.py --weights $x.pt --device $di  # detect official
    python detect.py --weights weights/last.pt --device $di  # detect custom
    python test.py --weights $x.pt --device $di # test official
    python test.py --weights weights/last.pt --device $di # test custom
  done
  python models/yolo.py --cfg $x.yaml # inspect
  python models/export.py --weights $x.pt --img 640 --batch 1 # export
done
```

**Comment by NanoCode012** [comment]
Sure. 

Edit: I ran them. Besides the error from `weights/last.pt` (due to it being moved to `runs` directory, there was an error `detect` and `test` with my new commit, but I fixed the latter. Unit test works.

Edit 2: Since I finished Magic 4 GPU DDP, I set Magic 1 and 2 GPU DDP to run. I also ran Default 1 and 4 GPU for curiosity.

Edit 3: I may be getting some bottleneck because time per epoch is around 15-16 mins now equally for 1-4 GPU for Default.

**Comment by NanoCode012** [comment]
@MagicFrogSJTU , all my machines is running right now, so I can't test this, but let's say if we want to use GPU 3 and 4 to run in DDP, how would the command work for 2 GPU?

`python -m torch.distributed.launch --nproc_per_node 2 ... --device 3,4`

Would `torch.distributed.launch` call GPU 0,1 or 3,4? Or would there be error because device 3,4 is not found because it launches the process first?

**Comment by MagicFrogSJTU** [comment]
> @MagicFrogSJTU , all my machines is running right now, so I can't test this, but let's say if we want to use GPU 3 and 4 to run in DDP, how would the command work for 2 GPU?
> 
> `python -m torch.distributed.launch --nproc_per_node 2 ... --device 3,4`
> 
> Would `torch.distributed.launch` call GPU 0,1 or 3,4? Or would there be error because device 3,4 is not found because it launches the process first?

@NanoCode012 
`python -m torch.distributed.launch --nproc_per_node 2 ... --device 3,4` will run 2-GPU DDP on gpu3,4.
If you have another DDP training on the same machine, let's say, on gpu 0,1,
you shoule use another master_port rather than default: `python -m torch.distributed.launch --master_port 42342 --nproc_per_node 2 ... --device 3,4`. Here 42342 is just a random port, use any number you like.

**Comment by NanoCode012** [comment]
@MagicFrogSJTU , hello, can we talk about the merge here instead? I do not want to fill that PR with our chat. I've already pushed the earlier script to the branch `_squashed` as a normal merge and convoluted that branch. Should you remake the branch? Sorry.

**Comment by NanoCode012** [comment]
Btw, we have not cleaned the output. For example, I was thinking of adding a `dist.barrier` before the start of the first epoch because some process would be faster than others and cause output to look like ,

![image](https://user-images.githubusercontent.com/9899957/87644497-6a32bd80-c776-11ea-972e-e2cd2fba9b1b.png)

I also think that we should only print `opt`, `hyp`, `model summary` and `GPU summary` once.

**Comment by MagicFrogSJTU** [comment]
> Btw, we have not cleaned the output. For example, I was thinking of adding a `dist.barrier` before the start of the first epoch because some process would be faster than others and cause output to look like ,
> 
> ![image](https://user-images.githubusercontent.com/9899957/87644497-6a32bd80-c776-11ea-972e-e2cd2fba9b1b.png)
> 
> I also think that we should only print `opt`, `hyp`, `model summary` and `GPU summary` once.

Yes, I think so. But we can leave these for the future. 
The better solution is to use logging for all output instead of printing them. With special logging configuration, you can implicitly output only the first process's log without explicitly `if local_rank in [-1, 0]`.
I suggest we finish this PR first, and then improve it. This has been too hard to maintain, especailly merging the master.

**Comment by MagicFrogSJTU** [comment]
> Btw, we have not cleaned the output. For example, I was thinking of adding a `dist.barrier` before the start of the first epoch because some process would be faster than others and cause output to look like ,
> 
> ![image](https://user-images.githubusercontent.com/9899957/87644497-6a32bd80-c776-11ea-972e-e2cd2fba9b1b.png)
> 
> I also think that we should only print `opt`, `hyp`, `model summary` and `GPU summary` once.

can't you just `git push -f $BRANCH`?

**Comment by MagicFrogSJTU** [comment]
> @MagicFrogSJTU , hello, can we talk about the merge here instead? I do not want to fill that PR with our chat. I've already pushed the earlier script to the branch `_squashed` as a normal merge and convoluted that branch. Should you remake the branch? Sorry.

can't you just `git push -f $BRANCH`?

**Comment by MagicFrogSJTU** [comment]
@NanoCode012 Or you just push it as another branch. I will do the rest.

**Comment by NanoCode012** [comment]
> @NanoCode012 Or you just push it as another branch. I will do the rest.

I'm sorry. I'm a bit confused. I pushed the merge into `_squashed`. There is nothing to update in `ddp_fixed`

**Comment by MagicFrogSJTU** [comment]
> > @NanoCode012 Or you just push it as another branch. I will do the rest.
> 
> I'm sorry. I'm a bit confused. I pushed the merge into `_squashed`. There is nothing to update in `ddp_fixed`

I have done it for you. Check that if your name is in the commit!

**Comment by NanoCode012** [comment]
Thank you very much.

**Comment by MagicFrogSJTU** [comment]
@NanoCode012 
Could you please run all the test, and tell Glenn that everything is okay?
I don't have any gpu machines still.

**Comment by NanoCode012** [comment]
Sure! I will run the UnitTest after I update the graph. The 8 GPU run just reached epoch 50.

**Comment by NanoCode012** [comment]
I've updated the graph for 8 GPU and set UnitTest to run. Is there a way to check if the _entire_ shell executed successfully? For now, I just manually check it for errors. I thought there was a way to use exit codes, but the only one I can find `echo $!` gives the exit code of the last operation.

**Comment by MagicFrogSJTU** [comment]
@NanoCode012 
```bash
# edit a file
vim something.sh
bash something.sh
```
```bash
# In something.sh
set -e  # This will make the script return instantly when encountering errors.
Your scripts.
```

**Comment by NanoCode012** [comment]
Ok. Test finished. There was an error when we `train.py` in DP mode 
`python train.py --epochs 3 --img 320 --device 0,1` because we do not `init_process_group`
https://github.com/MagicFrogSJTU/yolov5/blob/52a540d1f135416ac3a8fe14320bab6283cb441b/train.py#L406

```
Traceback (most recent call last):
  File "train.py", line 475, in <module>
    train(hyp, tb_writer, opt, device)
  File "train.py", line 406, in train
    dist.destroy_process_group() if device.type != 'cpu' and torch.cuda.device_count() > 1 else None
  File "python3.7/site-packages/torch/distributed/distributed_c10d.py", line 517, in destroy_process_group
    raise RuntimeError("Invalid process group specified")
RuntimeError: Invalid process group specified
```

I suggest adding a check using local rank instead to 
`dist.destroy_process_group() if local_rank not in [-1,0] else None`
Does DP need to destroy/close anything?

I didn't get the error before because the old unit test used only 1 device to train.

**Comment by MagicFrogSJTU** [comment]
> Ok. Test finished. There was an error when we `train.py` in DP mode
> `python train.py --epochs 3 --img 320 --device 0,1` because we do not `init_process_group`
> https://github.com/MagicFrogSJTU/yolov5/blob/52a540d1f135416ac3a8fe14320bab6283cb441b/train.py#L406
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 475, in <module>
>     train(hyp, tb_writer, opt, device)
>   File "train.py", line 406, in train
>     dist.destroy_process_group() if device.type != 'cpu' and torch.cuda.device_count() > 1 else None
>   File "python3.7/site-packages/torch/distributed/distributed_c10d.py", line 517, in destroy_process_group
>     raise RuntimeError("Invalid process group specified")
> RuntimeError: Invalid process group specified
> ```
> 
> I suggest adding a check using local rank instead to
> `dist.destroy_process_group() if local_rank not in [-1,0] else None`
> Does DP need to destroy/close anything?
> 
> I didn't get the error before because the old unit test used only 1 device to train.

DP doesn't need to close anything. Your improvement is right.

**Comment by NanoCode012** [comment]
Hello @MagicFrogSJTU , since we found out that issue was with the seed, I got curious and started up a new training with SyncBN. See below for table. 

|GPU | SynBN | 1 |2 |3 |4 |5 |6 |7| 8|
| --- | --- |--- |--- |--- |--- |--- |--- |--- |--- |
|2| Y|0.00997|- |-|- | -|-| - | - | 
|2| N|0.01064|- |-|- | -|-| - | - | 
|4| Y|0.0127|0.0636 |0.13 |0.192 | 0.241|0.276| 0.298 | 0.315 | 
|4| N |0.01239|0.06346 |0.1189 |0.1889 | 0.233|0.2678| 0.2902|0.3074 | 

It could also be randomness, but it's around **+0.8%** difference in only 8 epoch for 4 GPU.

From one thread https://github.com/pytorch/pytorch/issues/2584#issue-254261067 , it signifies value in SynBN at small batch sizes. Maybe SynBN could help on configurations with pairs of lower-end GPUs or GPUs with low memory <12 GB etc. Unfortunately, I'm not sure whether it's still true as that thread is old, and I don't have the machine to test.

What do you think? 

It also occurred to me that we didn't test this code at different batchsizes.

Edit: Add picture. 

![results (2)](https://user-images.githubusercontent.com/9899957/87744027-8edd7280-c814-11ea-92dc-a898ebabc1fc.png)

I guess it didn't do much (?) except for a bit in Precision and Objectness.

**Comment by MagicFrogSJTU** [comment]
> Hello @MagicFrogSJTU , since we found out that issue was with the seed, I got curious and started up a new training with SyncBN. See below for table.
> 
> GPU	SynBN	1	2	3	4	5	6	7	8
> 2	Y	0.00997	-	-	-	-	-	-	-
> 2	N	0.01064	-	-	-	-	-	-	-
> 4	Y	0.0127	0.0636	0.13	0.192	0.241	0.276	0.298	0.315
> 4	N	0.01239	0.06346	0.1189	0.1889	0.233	0.2678	0.2902	0.3074
> It could also be randomness, but it's around **+0.8%** difference in only 8 epoch for 4 GPU.
> 
> From one thread [pytorch/pytorch#2584 (comment)](https://github.com/pytorch/pytorch/issues/2584#issue-254261067) , it signifies value in SynBN at small batch sizes. Maybe SynBN could help on configurations with pairs of lower-end GPUs or GPUs with low memory <12 GB etc. Unfortunately, I'm not sure whether it's still true as that thread is old, and I don't have the machine to test.
> 
> What do you think?
> 
> It also occurred to me that we didn't test this code at different batchsizes.
> 
> Edit: Add picture.
> 
> ![results (2)](https://user-images.githubusercontent.com/9899957/87744027-8edd7280-c814-11ea-92dc-a898ebabc1fc.png)
> 
> I guess it didn't do much (?) except for a bit in Precision and Objectness.

Yes, SyncBN is vital for small-batch-size-on-each-gpu experiments. Actually, a batch size of 16 is big enough to keep the network trained normallly. Becuase it has been proved that the original single-gpu can be trained under batch size 16 (4 accumulations). In other words, if you set a smaller batch size, the performance difference can be significant.
In this PR, our target is too reproduce the normal performance. Therefore, there is no need to test inconventional hyper-parameters. But, since we have introduced the SyncBN module, you can take an experiment to further prove its correctness. I noticed your experiments on official PR include a 8-GPU one, and its performance is the lowest. Just tak a 8-GPU experiment with SyncBN, and see how big is the difference!

**Comment by NanoCode012** [comment]
> But, since we have introduced the SyncBN module, you can take an experiment to further prove its correctness. I noticed your experiments on official PR include a 8-GPU one, and its performance is the lowest. Just tak a 8-GPU experiment with SyncBN, and see how big is the difference!

Yep! I've set it to run because maybe the difference was because we didn't use SynBN. 64/8=8 batch-size per GPU. It should be in the range where SyncBN could help.

**Comment by NanoCode012** [comment]
Hello, I think we should remove `--sync-bn` as an argument and turn it on by default.

![results (3)](https://user-images.githubusercontent.com/9899957/87782294-71cc9200-c85c-11ea-9c8b-0de7364f5509.png)

Comparison using only SBN with default

![results (4)](https://user-images.githubusercontent.com/9899957/87783758-4eefad00-c85f-11ea-981b-d856770fd031.png)

Is it just me or is more GPU = slightly better?

**Comment by MagicFrogSJTU** [comment]
when total_batch_size is the same, DDP with SyncBN should have similar performance with default-single-gpu.
SyncBN is not of no cost. It would slow down the training speed. And for most cases with 2, 4 gpus, the performance difference is negligible. Therefore, I think SyncBN shouldn't be the default.
I think we should edit the README.md to provide how to activate DDP model and when and how should SyncBN is applied. You can discuss it with Glenn! I am currently out of hand!

**Comment by NanoCode012** [comment]
Thanks!

**Comment by NanoCode012** [comment]
Hi @MagicFrogSJTU , I've attempted to add mp_spawn. Thanks to the amazing foundation, there was not a lot of change. I have to still test it though, but running it with coco128 produced similar mAP to default branch. Need to test time.

https://github.com/MagicFrogSJTU/yolov5/tree/feature/mp_spawn

**Comment by MagicFrogSJTU** [comment]
> Hi @MagicFrogSJTU , I've attempted to add mp_spawn. Thanks to the amazing foundation, there was not a lot of change. I have to still test it though, but running it with coco128 produced similar mAP to default branch. Need to test time.
> 
> https://github.com/MagicFrogSJTU/yolov5/tree/feature/mp_spawn

great! Hope it works!
``` python
    # Exponential moving average
    # From https://github.com/rwightman/pytorch-image-models/blob/master/train.py:
    # "Important to create EMA model after cuda(), DP wrapper, and AMP but before SyncBN and DDP wrapper"
    # chenyzsjtu: ema should be placed before after SyncBN. As SyncBN introduces new modules.
    if opt.sync_bn and device.type != 'cpu' and local_rank != -1:
        print("SyncBN activated!")
        model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model).to(device)
```
I havn't tested what difference would DP's position make, so you should test the DP mode now that you have changed its position.

**Comment by NanoCode012** [comment]
> I havn't tested what difference would DP's position make, so you should test the DP mode now that you have changed its position.

Yep. That's one of the few things I worried when changing it. Good news is that mAP and time is roughly the same for DDP mode!

Edit: I've kept the code base changes as minimal as possible for now, for me to just experience mp.spawn. Will cleanup for readability later.

**Comment by NanoCode012** [comment]
Do you have a link where to implement the "logging" that you mentioned? I'm not sure what you mean by that. I have a feeling that we have to change the code in many places for the logging to work, if you mean to use an external lib.

**Comment by MagicFrogSJTU** [comment]
> Do you have a link where to implement the "logging" that you mentioned? I'm not sure what you mean by that. I have a feeling that we have to change the code in many places for the logging to work, if you mean to use an external lib.

Use log rather than print. It's better to ask glenn to agree on this first. 
dllogger
[https://github.com/NVIDIA/dllogger]()
[https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/LanguageModeling/BERT/run_pretraining.py]()

**Comment by MagicFrogSJTU** [comment]
> Do you have a link where to implement the "logging" that you mentioned? I'm not sure what you mean by that. I have a feeling that we have to change the code in many places for the logging to work, if you mean to use an external lib.

But we don't have to use dllogger actually.
The python inner class `logging` can do the same thing. We can use this first. Are you familiar with `logging`?

Edit 0:
After a short thought, I think we should use `logging` rather than `dllogger`. The latter one seems over-complicated and only gets several stars on github.
What do you think?

**Comment by NanoCode012** [comment]
Nope. I've never used it. Will check it out. This would be a large overhaul. Would be an entire new PR.

Edit: `dllogger` : I think using more external libs should be avoided.

**Comment by MagicFrogSJTU** [comment]
> Nope. I've never used it. Will check it out. This would be a large overhaul. Would be an entire new PR.

Yes. Not difficult though. Just need time to learn. Do it if you are willing to learn. If not, I can do this job.

**Comment by NanoCode012** [comment]
I'm not sure how `logging` would help in this situation, compared to `if local_rank not in [-1,0]: print()`

From my brief look, `logging` has different levels of severity. Do you mean to output those on Master GPU to a higher severity and those on other GPUs to lower severity and only output from a certain threshold(master gpu) ?

Edit: Hm, I re-read your comment in train.py and checked the example on BERT, they always enclose the logger in `if ismainprocess()`, is there a benefit?

**Comment by MagicFrogSJTU** [comment]
> I'm not sure how `logging` would help in this situation, compared to `if local_rank not in [-1,0]: print()`
> 
> From my brief look, `logging` has different levels of severity. Do you mean to output those on Master GPU to a higher severity and those on other GPUs to lower severity and only output from a certain threshold(master gpu) ?
> 
> Edit: Hm, I re-read your comment in train.py and checked the example on BERT, they always enclose the logger in `if ismainprocess()`, is there a benefit?

Sorry, my bad. It should be [example](https://github.com/huggingface/transformers/blob/master/examples/text-classification/run_glue.py).
I mix some similar things lol. Using different levels of severity is simple and powerful!

**Comment by NanoCode012** [comment]
These are my results for launch vs spawn.

![image](https://user-images.githubusercontent.com/9899957/88008066-94e79200-cb39-11ea-968f-c0834c290f0e.png)

![image](https://user-images.githubusercontent.com/9899957/88008082-9e70fa00-cb39-11ea-9389-475f0cac4205.png)

I think spawn creates quite varied results. For eg, for the first time I ran 4 DDP, I got an average of 350s. (Then a bit code change for DP to work). The second time, it is 375s. Third time, 387. Am I doing something wrong?

**Comment by MagicFrogSJTU** [comment]
> These are my results for launch vs spawn.
> 
> ![image](https://user-images.githubusercontent.com/9899957/88008066-94e79200-cb39-11ea-968f-c0834c290f0e.png)
> 
> ![image](https://user-images.githubusercontent.com/9899957/88008082-9e70fa00-cb39-11ea-9389-475f0cac4205.png)
> 
> I think spawn creates quite varied results. For eg, for the first time I ran 4 DDP, I got an average of 350s. (Then a bit code change for DP to work). The second time, it is 375s. Third time, 387. Am I doing something wrong?

I will look over your code later. It's interesting that spawn is slower. I once expected they would be the same.

**Comment by MagicFrogSJTU** [comment]
> > These are my results for launch vs spawn.
> > ![image](https://user-images.githubusercontent.com/9899957/88008066-94e79200-cb39-11ea-968f-c0834c290f0e.png)
> > ![image](https://user-images.githubusercontent.com/9899957/88008082-9e70fa00-cb39-11ea-9389-475f0cac4205.png)
> > I think spawn creates quite varied results. For eg, for the first time I ran 4 DDP, I got an average of 350s. (Then a bit code change for DP to work). The second time, it is 375s. Third time, 387. Am I doing something wrong?
> 

I will look over your code later. It's interesting that spawn is slower. I once expected they would be the same.
which branch are you in now?


>  think spawn creates quite varied results. For eg, for the first time I ran 4 DDP, I got an average of 350s. (Then a bit code change for DP to work). The second time, it is 375s. Third time, 387. Am I doing something wrong?

Is it withn random fluctuation range? I am not quite sure

**Comment by MagicFrogSJTU** [comment]
@NanoCode012 
I think we should create an new issue. The original ones have too many comments. What do you think?

**Comment by NanoCode012** [comment]
> I think we should create an new issue. The original ones have too many comments. What do you think?

Yep.  I was thinking the same for the PR in the main repo.

**Comment by MagicFrogSJTU** [comment]
> > I think we should create an new issue. The original ones have too many comments. What do you think?
> 
> Yep. I was thinking the same for the PR in the main repo.

I am talking with new issue in the main repos actually. But, both is okay!

**Comment by MagicFrogSJTU** [comment]
> > I think we should create an new issue. The original ones have too many comments. What do you think?
> 
> Yep. I was thinking the same for the PR in the main repo.

You can collect your code change and make a new PR in the main repos! I have created the issue!
